##################################################################################################
# allure-report service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: allure-report
  labels:
    app: allure-report
    service: allure-report
spec:
  ports:
    - port: 5252
      name: ui
    - port: 5050
      name: http  
  selector:
    app: allure-report
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: allure-test-report
  labels:
    account: allure-report
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: allure-report
  labels:
    app: allure-report
    # version: v1
spec:
  selector:
    matchLabels:
      app: allure-report
      # version: v1
  template:
    metadata:
      labels:
        app: allure-report
        # version: v1
    spec:
      serviceAccountName: allure-report
      containers:
        - name: allure
          image: asia.gcr.io/projectname/allure:latest
          imagePullPolicy: Always
          env:
            # - name: CHECK_RESULTS_EVERY_SECONDS
            #   value: '1'
            - name: KEEP_HISTORY
              value: '1'
            - name: DEV_MODE
              value: '0'
            - name: CHECK_RESULTS_EVERY_SECONDS
              value: 'NONE'
            - name: SECURITY_ENABLED
              value: '1'
            - name: KEEP_HISTORY_LATEST
              value: '5'
      #URL_PREFIX: "/my-prefix"
            - name: SECURITY_USER
              value: 'username'
            - name: SECURITY_PASS
              value: 'password'
            - name: SECURITY_VIEWER_USER
              value: 'view_user'
            - name: SECURITY_VIEWER_PASS
              value: '10'      
            - name: MAKE_VIEWER_ENDPOINTS_PUBLIC
              value: '0'
            - name: OPTIMIZE_STORAGE
              value: '0'
            - name: API_RESPONSE_LESS_VERBOSE
              value: '0'
            - name: TLS
              value: '0'
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          ports:
            - containerPort: 5050
          resources:
            requests:
              memory: "80Mi"
            limits:
              memory: "100Mi"
          volumeMounts:
        - name: allureui
          image: frankescobar/allure-docker-service-ui
          imagePullPolicy: Always
          env:
            - name: ALLURE_DOCKER_PUBLIC_API_URL
              value: https://domain.com
            - name: ALLURE_DOCKER_PUBLIC_API_URL_PREFIX
              value: ''
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          ports:
            - containerPort: 5252
          resources:
            requests:
              memory: "80Mi"
            limits:
              memory: "100Mi"
          volumeMounts:
      restartPolicy: Always


        